---
title: "Untitled"
author: '''Nethalie Betti Pillippuge'''
date: "2025-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
```

#Reading in the csv file
```{r}
species_path = read.csv("/Users/tneth/OneDrive/Documents/MSc_AppBio/MSc_project/outputs/dataset/fungi_exp_species_data/output_with_species2.csv")
species_df = as.data.frame(species_path)

#view(species_df)

#Extracting the genus from species names
species_df$genus = sapply(strsplit(species_df$Species_name, " "), `[`, 1)
#print(genus)


species_counts <- species_df %>%
  group_by(Species_name, genus) %>%
  summarise(Experiment_number = sum(Experiment_number), .groups = "drop")


mean_exp <- mean(species_counts$Experiment_number, na.rm = TRUE)
print(mean_exp)


genus_counts <- species_df %>%
  group_by(genus) %>%
  summarise(Experiment_number = sum(Experiment_number), .groups = "drop")


genus_counts$genus <- reorder(genus_counts$genus, -genus_counts$Experiment_number)
View(genus_counts)

mean_genus <- mean(genus_counts$Experiment_number, na.rm = TRUE)
print(mean_genus)



```

#Plotting a histogram/bar chart to display the counts of experiment number
```{r}
ggplot(data = species_counts, mapping = aes(x=Experiment_number)) +
  geom_histogram(bins = 50, boundary = 0, fill="deepskyblue", color="black") + 

                scale_x_continuous(limits = c(0, 1300), breaks = seq(0, 1300, 50)) +
                scale_y_continuous(breaks = seq(0, 120, 10)) +  
                coord_cartesian(ylim = c(0, 120)) +
    
                ggtitle("Histogram showing frequency of experiment numbers") 



ggplot(data = genus_counts, aes(x = genus, y = Experiment_number)) +
   geom_bar(stat = "identity", fill = "lightcoral") +
  labs(
    title = "Experiment number per genus",
    x = "Genus",
    y = "Experiment number"
  ) +
  theme_minimal() +
    theme(axis.text.x = element_text(hjust = 0.5))


```
```{r}

#Filtered histogram showing distribution of experiments <550

filter_counts <- species_counts %>%
  filter(experiment_number <= 550)

ggplot(data = filter_counts, mapping = aes(x=experiment_number)) +
  geom_histogram(bins = 50, boundary = 0, fill="deepskyblue", color="black") + 

                scale_x_continuous(limits = c(0, 550), breaks = seq(0, 550, 10)) +
                scale_y_continuous(breaks = seq(0, 120, 10)) +  
                coord_cartesian(ylim = c(0, 60)) +
                ggtitle("Histogram showing frequency of experiment numbers")
```
```{r}
median_no = as.numeric(species_df$Experiment_number)
median = print(median(median_no, na.rm = TRUE))

print(sum(is.na(species_df$Experiment_number)))
print(unique(species_df$Experiment_number))
```

#Bar chart showing experiment number per species
```{r}
ggplot(species_counts, aes(x = reorder(Species_name, count), y = count, fill = genus)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(
    x = " ",
    y = "Experiment number",
    title = "Number of Experiments per Species",
    labs(fill = "Genus"),
    
  ) +
  
  theme(
    axis.text.x = element_text(" "),
    legend.text = element_text(size = 0), 
    legend.key.size = unit(0.5, "points"),
    legend.position = ("right")
)

ggplot(data = species_df, aes(x=species_df$Experiment_number)) +
  geom_density()

```

